// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  // MongoDB does not support migrations; use `prisma db push` instead
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
